### PR TITLE
Pubbystation adds pharmacy area

### PR DESCRIPTION
**Pull request by ghost**
minor change to pubbystation gives chemistry a pharmacy area rather than chemistry just being a plumbing factory that doctors can access

### CODE REVIEW

**Comment by ghost** [comment]
gfdsdsd

**Comment by SmArtKar** [comment]
You're on the wrong github buddy. You know, we also no longer have pubbystation.

**Comment by JohnFulpWillard** [comment]
Atmos pipes leading to the maint door in pharmacy is off

**Comment by ghost** [comment]
you right

**Comment by Maurukas** [comment]
Sorry for the delay, I broke my local repo.

**Pull request merged**
